/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#ifndef _recon_recon_H
#define _recon_recon_H

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include <map>

namespace recon {

/**
 * This is the main C++ entry point of this AI.
 * 
 * @author	Robin Vobruba <hoijui.quaero@gmail.com>
 */
class Recon {



private:
	springai::OOAICallback* callback;
	int skirmishAIId;
    int numPlanes;
    std::string prefix;
    springai::UnitDef* reconUnitDef;
    springai::Unit* hq;
    void AddPlane(int unitId);
    springai::Unit* GetFriendlyUnitById(int id) const;
    springai::Unit* GetEnemyUnitById(int id) const;
    std::vector<std::vector<springai::AIFloat3> > waypoints;
    std::map<int,int> u2i;
    std::vector<int> ustat;
	std::vector<springai::Unit*> friends;
	int frame;
public:
	Recon(springai::OOAICallback* callback);
	~Recon();

	int HandleEvent(int topic, const void* data);
}; // class Recon

} // namespace recon

#endif // _recon_recon_H

