/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#ifndef _incumbent_incumbent_H
#define _incumbent_incumbent_H

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"

namespace incumbent {

/**
 * This is the main C++ entry point of this AI.
 * 
 * @author	Robin Vobruba <hoijui.quaero@gmail.com>
 */
class Incumbent {

private:
	springai::OOAICallback* callback;
	int skirmishAIId;

public:
	Incumbent(springai::OOAICallback* callback);
	~Incumbent();

	int HandleEvent(int topic, const void* data);
}; // class Incumbent

} // namespace incumbent

#endif // _incumbent_incumbent_H

